//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanBoTheoDoiVanBan
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdTheoDoiVanBan { get; set; }
        public Nullable<System.Guid> IdCanBo { get; set; }
        public Nullable<System.DateTime> DateNgayNhan { get; set; }
        public Nullable<System.DateTime> DateNgayXong { get; set; }
        public string newcolumn { get; set; }
    }
}
