//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDVanBanDen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GDVanBanDen()
        {
            this.TheoDoiVanBan = new HashSet<TheoDoiVanBan>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> DateNgayNhan { get; set; }
        public Nullable<System.Guid> IdCoQuanBanHanhVanBan { get; set; }
        public Nullable<System.Guid> IdLoaiVanBan { get; set; }
        public Nullable<System.Guid> IdLinhVucBanHanh { get; set; }
        public string SoVanBan { get; set; }
        public Nullable<System.DateTime> DateNgayPhatHanh { get; set; }
        public string TrichYeuVanBan { get; set; }
        public string CommentGD { get; set; }
        public string NumberSoCongVan { get; set; }
        public Nullable<System.Guid> IDDonViChuTri { get; set; }
        public Nullable<System.Guid> IDDonVIPhoiHop { get; set; }
        public Nullable<System.DateTime> DateNgayChiDao { get; set; }
        public Nullable<System.DateTime> DateNgayPhaiHoanThanh { get; set; }
        public Nullable<bool> PhaiBaoCao { get; set; }
        public string NguoiNhanVanBan { get; set; }
        public Nullable<System.DateTime> DateChuyenVanBanToiDonVi { get; set; }
        public string HoanThanh { get; set; }
        public string ChuaHoanThanh { get; set; }
        public string DangThucHien { get; set; }
        public string ChuaThucHien { get; set; }
        public string ThucHienCham { get; set; }
        public string KetThucCongViec { get; set; }
        public string TomTatKetQua { get; set; }
        public string Patition { get; set; }
        public string TaiLIeuDinhKem { get; set; }
        public Nullable<System.Guid> IdCanBoNhap { get; set; }
        public Nullable<System.DateTime> DateHoanThanh { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheoDoiVanBan> TheoDoiVanBan { get; set; }
    }
}
