//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyCongViecEntities : DbContext
    {
        public QuanLyCongViecEntities()
            : base("name=QuanLyCongViecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CanBo> CanBo { get; set; }
        public virtual DbSet<GDKyBanHanh> GDKyBanHanh { get; set; }
        public virtual DbSet<LanhDaoDonVi> LanhDaoDonVi { get; set; }
        public virtual DbSet<LinhVucBanHanh> LinhVucBanHanh { get; set; }
        public virtual DbSet<LoaiVanBan> LoaiVanBan { get; set; }
        public virtual DbSet<CanBoTheoDoiVanBan> CanBoTheoDoiVanBan { get; set; }
        public virtual DbSet<TheoDoiVanBan> TheoDoiVanBan { get; set; }
        public virtual DbSet<ViewTheoDoiVanBan> ViewTheoDoiVanBan { get; set; }
        public virtual DbSet<GDVanBanDen> GDVanBanDen { get; set; }
        public virtual DbSet<CoQuanBanHanhVanBan> CoQuanBanHanhVanBan { get; set; }
        public virtual DbSet<DonVi> DonVi { get; set; }
        public virtual DbSet<ViewDonViVaCoQuan> ViewDonViVaCoQuan { get; set; }
        public virtual DbSet<ViewGDKyBanHanh> ViewGDKyBanHanh { get; set; }
        public virtual DbSet<ViewGDVanBanDen> ViewGDVanBanDen { get; set; }
    
        public virtual int AddGDKyBanHanh(Nullable<System.Guid> id, Nullable<System.Guid> idLinhVucBanHanh, Nullable<System.Guid> idLoaiVanBan, Nullable<System.Guid> idDonViThamMuu, Nullable<System.Guid> idLanhDaoPhuTrach, string canBoThamMuu, Nullable<System.DateTime> dateTrinhVanBan, Nullable<System.DateTime> dateKyVanBan, string numberVanBan, Nullable<System.DateTime> dateVanBan, string trichYeuVanBan, string partions, string taiLieuDinhKem, Nullable<System.Guid> idCanBoNhap, Nullable<System.DateTime> createDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var idLinhVucBanHanhParameter = idLinhVucBanHanh.HasValue ?
                new ObjectParameter("IdLinhVucBanHanh", idLinhVucBanHanh) :
                new ObjectParameter("IdLinhVucBanHanh", typeof(System.Guid));
    
            var idLoaiVanBanParameter = idLoaiVanBan.HasValue ?
                new ObjectParameter("IdLoaiVanBan", idLoaiVanBan) :
                new ObjectParameter("IdLoaiVanBan", typeof(System.Guid));
    
            var idDonViThamMuuParameter = idDonViThamMuu.HasValue ?
                new ObjectParameter("IdDonViThamMuu", idDonViThamMuu) :
                new ObjectParameter("IdDonViThamMuu", typeof(System.Guid));
    
            var idLanhDaoPhuTrachParameter = idLanhDaoPhuTrach.HasValue ?
                new ObjectParameter("IdLanhDaoPhuTrach", idLanhDaoPhuTrach) :
                new ObjectParameter("IdLanhDaoPhuTrach", typeof(System.Guid));
    
            var canBoThamMuuParameter = canBoThamMuu != null ?
                new ObjectParameter("CanBoThamMuu", canBoThamMuu) :
                new ObjectParameter("CanBoThamMuu", typeof(string));
    
            var dateTrinhVanBanParameter = dateTrinhVanBan.HasValue ?
                new ObjectParameter("DateTrinhVanBan", dateTrinhVanBan) :
                new ObjectParameter("DateTrinhVanBan", typeof(System.DateTime));
    
            var dateKyVanBanParameter = dateKyVanBan.HasValue ?
                new ObjectParameter("DateKyVanBan", dateKyVanBan) :
                new ObjectParameter("DateKyVanBan", typeof(System.DateTime));
    
            var numberVanBanParameter = numberVanBan != null ?
                new ObjectParameter("NumberVanBan", numberVanBan) :
                new ObjectParameter("NumberVanBan", typeof(string));
    
            var dateVanBanParameter = dateVanBan.HasValue ?
                new ObjectParameter("DateVanBan", dateVanBan) :
                new ObjectParameter("DateVanBan", typeof(System.DateTime));
    
            var trichYeuVanBanParameter = trichYeuVanBan != null ?
                new ObjectParameter("TrichYeuVanBan", trichYeuVanBan) :
                new ObjectParameter("TrichYeuVanBan", typeof(string));
    
            var partionsParameter = partions != null ?
                new ObjectParameter("partions", partions) :
                new ObjectParameter("partions", typeof(string));
    
            var taiLieuDinhKemParameter = taiLieuDinhKem != null ?
                new ObjectParameter("TaiLieuDinhKem", taiLieuDinhKem) :
                new ObjectParameter("TaiLieuDinhKem", typeof(string));
    
            var idCanBoNhapParameter = idCanBoNhap.HasValue ?
                new ObjectParameter("IdCanBoNhap", idCanBoNhap) :
                new ObjectParameter("IdCanBoNhap", typeof(System.Guid));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddGDKyBanHanh", idParameter, idLinhVucBanHanhParameter, idLoaiVanBanParameter, idDonViThamMuuParameter, idLanhDaoPhuTrachParameter, canBoThamMuuParameter, dateTrinhVanBanParameter, dateKyVanBanParameter, numberVanBanParameter, dateVanBanParameter, trichYeuVanBanParameter, partionsParameter, taiLieuDinhKemParameter, idCanBoNhapParameter, createDateParameter);
        }
    
        public virtual int AddLanhDaoDonVi(Nullable<System.Guid> id, string tenLanhDao, string chucVu, Nullable<System.Guid> idDonVi, Nullable<System.DateTime> createdate, Nullable<bool> active)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var tenLanhDaoParameter = tenLanhDao != null ?
                new ObjectParameter("TenLanhDao", tenLanhDao) :
                new ObjectParameter("TenLanhDao", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var idDonViParameter = idDonVi.HasValue ?
                new ObjectParameter("IdDonVi", idDonVi) :
                new ObjectParameter("IdDonVi", typeof(System.Guid));
    
            var createdateParameter = createdate.HasValue ?
                new ObjectParameter("Createdate", createdate) :
                new ObjectParameter("Createdate", typeof(System.DateTime));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddLanhDaoDonVi", idParameter, tenLanhDaoParameter, chucVuParameter, idDonViParameter, createdateParameter, activeParameter);
        }
    
        public virtual int AddLinhVucBanHanh(Nullable<System.Guid> id, string codeLinhVuc, string nameLinhVuc, Nullable<System.DateTime> createdate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var codeLinhVucParameter = codeLinhVuc != null ?
                new ObjectParameter("CodeLinhVuc", codeLinhVuc) :
                new ObjectParameter("CodeLinhVuc", typeof(string));
    
            var nameLinhVucParameter = nameLinhVuc != null ?
                new ObjectParameter("NameLinhVuc", nameLinhVuc) :
                new ObjectParameter("NameLinhVuc", typeof(string));
    
            var createdateParameter = createdate.HasValue ?
                new ObjectParameter("Createdate", createdate) :
                new ObjectParameter("Createdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddLinhVucBanHanh", idParameter, codeLinhVucParameter, nameLinhVucParameter, createdateParameter);
        }
    
        public virtual int AddLoaiVanBan(Nullable<System.Guid> id, string codeVanBan, string nameVanBan, Nullable<System.DateTime> createdate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var codeVanBanParameter = codeVanBan != null ?
                new ObjectParameter("CodeVanBan", codeVanBan) :
                new ObjectParameter("CodeVanBan", typeof(string));
    
            var nameVanBanParameter = nameVanBan != null ?
                new ObjectParameter("NameVanBan", nameVanBan) :
                new ObjectParameter("NameVanBan", typeof(string));
    
            var createdateParameter = createdate.HasValue ?
                new ObjectParameter("Createdate", createdate) :
                new ObjectParameter("Createdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddLoaiVanBan", idParameter, codeVanBanParameter, nameVanBanParameter, createdateParameter);
        }
    
        public virtual int DeleteGDKyBanHanh(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteGDKyBanHanh", idParameter);
        }
    
        public virtual int DeleteLanhDaoDonVi(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteLanhDaoDonVi", idParameter);
        }
    
        public virtual int DeleteLinhVucBanHanh(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteLinhVucBanHanh", idParameter);
        }
    
        public virtual int DeleteLoaiVanBan(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteLoaiVanBan", idParameter);
        }
    
        public virtual int EditGDKyBanHanh(Nullable<System.Guid> id, Nullable<System.Guid> idLinhVucBanHanh, Nullable<System.Guid> idLoaiVanBan, Nullable<System.Guid> idDonViThamMuu, Nullable<System.Guid> idLanhDaoPhuTrach, string canBoThamMuu, Nullable<System.DateTime> dateTrinhVanBan, Nullable<System.DateTime> dateKyVanBan, string numberVanBan, Nullable<System.DateTime> dateVanBan, string trichYeuVanBan, string partions, string taiLieuDinhKem)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var idLinhVucBanHanhParameter = idLinhVucBanHanh.HasValue ?
                new ObjectParameter("IdLinhVucBanHanh", idLinhVucBanHanh) :
                new ObjectParameter("IdLinhVucBanHanh", typeof(System.Guid));
    
            var idLoaiVanBanParameter = idLoaiVanBan.HasValue ?
                new ObjectParameter("IdLoaiVanBan", idLoaiVanBan) :
                new ObjectParameter("IdLoaiVanBan", typeof(System.Guid));
    
            var idDonViThamMuuParameter = idDonViThamMuu.HasValue ?
                new ObjectParameter("IdDonViThamMuu", idDonViThamMuu) :
                new ObjectParameter("IdDonViThamMuu", typeof(System.Guid));
    
            var idLanhDaoPhuTrachParameter = idLanhDaoPhuTrach.HasValue ?
                new ObjectParameter("IdLanhDaoPhuTrach", idLanhDaoPhuTrach) :
                new ObjectParameter("IdLanhDaoPhuTrach", typeof(System.Guid));
    
            var canBoThamMuuParameter = canBoThamMuu != null ?
                new ObjectParameter("CanBoThamMuu", canBoThamMuu) :
                new ObjectParameter("CanBoThamMuu", typeof(string));
    
            var dateTrinhVanBanParameter = dateTrinhVanBan.HasValue ?
                new ObjectParameter("DateTrinhVanBan", dateTrinhVanBan) :
                new ObjectParameter("DateTrinhVanBan", typeof(System.DateTime));
    
            var dateKyVanBanParameter = dateKyVanBan.HasValue ?
                new ObjectParameter("DateKyVanBan", dateKyVanBan) :
                new ObjectParameter("DateKyVanBan", typeof(System.DateTime));
    
            var numberVanBanParameter = numberVanBan != null ?
                new ObjectParameter("NumberVanBan", numberVanBan) :
                new ObjectParameter("NumberVanBan", typeof(string));
    
            var dateVanBanParameter = dateVanBan.HasValue ?
                new ObjectParameter("DateVanBan", dateVanBan) :
                new ObjectParameter("DateVanBan", typeof(System.DateTime));
    
            var trichYeuVanBanParameter = trichYeuVanBan != null ?
                new ObjectParameter("TrichYeuVanBan", trichYeuVanBan) :
                new ObjectParameter("TrichYeuVanBan", typeof(string));
    
            var partionsParameter = partions != null ?
                new ObjectParameter("partions", partions) :
                new ObjectParameter("partions", typeof(string));
    
            var taiLieuDinhKemParameter = taiLieuDinhKem != null ?
                new ObjectParameter("TaiLieuDinhKem", taiLieuDinhKem) :
                new ObjectParameter("TaiLieuDinhKem", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditGDKyBanHanh", idParameter, idLinhVucBanHanhParameter, idLoaiVanBanParameter, idDonViThamMuuParameter, idLanhDaoPhuTrachParameter, canBoThamMuuParameter, dateTrinhVanBanParameter, dateKyVanBanParameter, numberVanBanParameter, dateVanBanParameter, trichYeuVanBanParameter, partionsParameter, taiLieuDinhKemParameter);
        }
    
        public virtual int EditLanhDaoDonVi(Nullable<System.Guid> id, string tenLanhDao, string chucVu, Nullable<bool> actived)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var tenLanhDaoParameter = tenLanhDao != null ?
                new ObjectParameter("TenLanhDao", tenLanhDao) :
                new ObjectParameter("TenLanhDao", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var activedParameter = actived.HasValue ?
                new ObjectParameter("Actived", actived) :
                new ObjectParameter("Actived", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditLanhDaoDonVi", idParameter, tenLanhDaoParameter, chucVuParameter, activedParameter);
        }
    
        public virtual int EditLinhVucBanHanh(Nullable<System.Guid> id, string codeLinhVuc, string nameLinhVuc)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var codeLinhVucParameter = codeLinhVuc != null ?
                new ObjectParameter("CodeLinhVuc", codeLinhVuc) :
                new ObjectParameter("CodeLinhVuc", typeof(string));
    
            var nameLinhVucParameter = nameLinhVuc != null ?
                new ObjectParameter("NameLinhVuc", nameLinhVuc) :
                new ObjectParameter("NameLinhVuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditLinhVucBanHanh", idParameter, codeLinhVucParameter, nameLinhVucParameter);
        }
    
        public virtual int EditLoaiVanBan(Nullable<System.Guid> id, string codeVanBan, string nameVanBan)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var codeVanBanParameter = codeVanBan != null ?
                new ObjectParameter("CodeVanBan", codeVanBan) :
                new ObjectParameter("CodeVanBan", typeof(string));
    
            var nameVanBanParameter = nameVanBan != null ?
                new ObjectParameter("NameVanBan", nameVanBan) :
                new ObjectParameter("NameVanBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditLoaiVanBan", idParameter, codeVanBanParameter, nameVanBanParameter);
        }
    
        public virtual ObjectResult<GetAllCanBo_Result> GetAllCanBo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCanBo_Result>("GetAllCanBo");
        }
    
        public virtual ObjectResult<GetDonViSearch_Result> GetDonViSearch()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDonViSearch_Result>("GetDonViSearch");
        }
    
        public virtual ObjectResult<GetOneGDKyBanHanh_Result> GetOneGDKyBanHanh(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneGDKyBanHanh_Result>("GetOneGDKyBanHanh", idParameter);
        }
    
        public virtual ObjectResult<GetOneLinhVucBanHanh_Result> GetOneLinhVucBanHanh(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneLinhVucBanHanh_Result>("GetOneLinhVucBanHanh", idParameter);
        }
    
        public virtual ObjectResult<GetOneLoaiVanBan_Result> GetOneLoaiVanBan(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneLoaiVanBan_Result>("GetOneLoaiVanBan", idParameter);
        }
    
        public virtual ObjectResult<searchlanhdaodonvi_Result> searchlanhdaodonvi(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchlanhdaodonvi_Result>("searchlanhdaodonvi", idParameter);
        }
    
        public virtual int AddTheoDoiVanBan(Nullable<System.Guid> id, Nullable<System.Guid> idGDVanBanDen, string canBoThuLy, string commentGD, string pGDPhuTrach, Nullable<System.Guid> idDonViChucNang, Nullable<System.Guid> idLanhDaoPhuTrach, string tienDoCongViec, string numBerDate, string taiLieuDinhKem, Nullable<System.DateTime> createdate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var idGDVanBanDenParameter = idGDVanBanDen.HasValue ?
                new ObjectParameter("IdGDVanBanDen", idGDVanBanDen) :
                new ObjectParameter("IdGDVanBanDen", typeof(System.Guid));
    
            var canBoThuLyParameter = canBoThuLy != null ?
                new ObjectParameter("CanBoThuLy", canBoThuLy) :
                new ObjectParameter("CanBoThuLy", typeof(string));
    
            var commentGDParameter = commentGD != null ?
                new ObjectParameter("CommentGD", commentGD) :
                new ObjectParameter("CommentGD", typeof(string));
    
            var pGDPhuTrachParameter = pGDPhuTrach != null ?
                new ObjectParameter("PGDPhuTrach", pGDPhuTrach) :
                new ObjectParameter("PGDPhuTrach", typeof(string));
    
            var idDonViChucNangParameter = idDonViChucNang.HasValue ?
                new ObjectParameter("IdDonViChucNang", idDonViChucNang) :
                new ObjectParameter("IdDonViChucNang", typeof(System.Guid));
    
            var idLanhDaoPhuTrachParameter = idLanhDaoPhuTrach.HasValue ?
                new ObjectParameter("IdLanhDaoPhuTrach", idLanhDaoPhuTrach) :
                new ObjectParameter("IdLanhDaoPhuTrach", typeof(System.Guid));
    
            var tienDoCongViecParameter = tienDoCongViec != null ?
                new ObjectParameter("TienDoCongViec", tienDoCongViec) :
                new ObjectParameter("TienDoCongViec", typeof(string));
    
            var numBerDateParameter = numBerDate != null ?
                new ObjectParameter("NumBerDate", numBerDate) :
                new ObjectParameter("NumBerDate", typeof(string));
    
            var taiLieuDinhKemParameter = taiLieuDinhKem != null ?
                new ObjectParameter("TaiLieuDinhKem", taiLieuDinhKem) :
                new ObjectParameter("TaiLieuDinhKem", typeof(string));
    
            var createdateParameter = createdate.HasValue ?
                new ObjectParameter("Createdate", createdate) :
                new ObjectParameter("Createdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddTheoDoiVanBan", idParameter, idGDVanBanDenParameter, canBoThuLyParameter, commentGDParameter, pGDPhuTrachParameter, idDonViChucNangParameter, idLanhDaoPhuTrachParameter, tienDoCongViecParameter, numBerDateParameter, taiLieuDinhKemParameter, createdateParameter);
        }
    
        public virtual int DeleteTheoDoiVanBan(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTheoDoiVanBan", idParameter);
        }
    
        public virtual int EditTheoDoiVanBan(Nullable<System.Guid> id, string canBoThuLy, string commentGD, string pGDPhuTrach, Nullable<System.Guid> idDonViChucNang, Nullable<System.Guid> idLanhDaoPhuTrach, string tienDoCongViec, string numBerDate, string taiLieuDinhKem)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var canBoThuLyParameter = canBoThuLy != null ?
                new ObjectParameter("CanBoThuLy", canBoThuLy) :
                new ObjectParameter("CanBoThuLy", typeof(string));
    
            var commentGDParameter = commentGD != null ?
                new ObjectParameter("CommentGD", commentGD) :
                new ObjectParameter("CommentGD", typeof(string));
    
            var pGDPhuTrachParameter = pGDPhuTrach != null ?
                new ObjectParameter("PGDPhuTrach", pGDPhuTrach) :
                new ObjectParameter("PGDPhuTrach", typeof(string));
    
            var idDonViChucNangParameter = idDonViChucNang.HasValue ?
                new ObjectParameter("IdDonViChucNang", idDonViChucNang) :
                new ObjectParameter("IdDonViChucNang", typeof(System.Guid));
    
            var idLanhDaoPhuTrachParameter = idLanhDaoPhuTrach.HasValue ?
                new ObjectParameter("IdLanhDaoPhuTrach", idLanhDaoPhuTrach) :
                new ObjectParameter("IdLanhDaoPhuTrach", typeof(System.Guid));
    
            var tienDoCongViecParameter = tienDoCongViec != null ?
                new ObjectParameter("TienDoCongViec", tienDoCongViec) :
                new ObjectParameter("TienDoCongViec", typeof(string));
    
            var numBerDateParameter = numBerDate != null ?
                new ObjectParameter("NumBerDate", numBerDate) :
                new ObjectParameter("NumBerDate", typeof(string));
    
            var taiLieuDinhKemParameter = taiLieuDinhKem != null ?
                new ObjectParameter("TaiLieuDinhKem", taiLieuDinhKem) :
                new ObjectParameter("TaiLieuDinhKem", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditTheoDoiVanBan", idParameter, canBoThuLyParameter, commentGDParameter, pGDPhuTrachParameter, idDonViChucNangParameter, idLanhDaoPhuTrachParameter, tienDoCongViecParameter, numBerDateParameter, taiLieuDinhKemParameter);
        }
    
        public virtual ObjectResult<GetOneTheoDoiVanBanDen_Result> GetOneTheoDoiVanBanDen(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneTheoDoiVanBanDen_Result>("GetOneTheoDoiVanBanDen", idParameter);
        }
    
        public virtual ObjectResult<GetAllTheoDoiVanBan_Result> GetAllTheoDoiVanBan(Nullable<System.Guid> idGDVanBanDen)
        {
            var idGDVanBanDenParameter = idGDVanBanDen.HasValue ?
                new ObjectParameter("IdGDVanBanDen", idGDVanBanDen) :
                new ObjectParameter("IdGDVanBanDen", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllTheoDoiVanBan_Result>("GetAllTheoDoiVanBan", idGDVanBanDenParameter);
        }
    
        public virtual ObjectResult<GetAllTheoDoiVanBan1_Result> GetAllTheoDoiVanBan1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllTheoDoiVanBan1_Result>("GetAllTheoDoiVanBan1");
        }
    
        public virtual ObjectResult<GetAllLinhVucBanHanh_Result> GetAllLinhVucBanHanh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllLinhVucBanHanh_Result>("GetAllLinhVucBanHanh");
        }
    
        public virtual ObjectResult<GetAllLanhDaoDonvi_Result> GetAllLanhDaoDonvi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllLanhDaoDonvi_Result>("GetAllLanhDaoDonvi");
        }
    
        public virtual ObjectResult<GetOneLanhDaoDonVi_Result> GetOneLanhDaoDonVi(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneLanhDaoDonVi_Result>("GetOneLanhDaoDonVi", idParameter);
        }
    
        public virtual ObjectResult<GetAllLoaiVanBan_Result> GetAllLoaiVanBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllLoaiVanBan_Result>("GetAllLoaiVanBan");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> CheckExistVanBanDen(string soVanBan, Nullable<System.DateTime> dateNgayPhatHanh)
        {
            var soVanBanParameter = soVanBan != null ?
                new ObjectParameter("SoVanBan", soVanBan) :
                new ObjectParameter("SoVanBan", typeof(string));
    
            var dateNgayPhatHanhParameter = dateNgayPhatHanh.HasValue ?
                new ObjectParameter("DateNgayPhatHanh", dateNgayPhatHanh) :
                new ObjectParameter("DateNgayPhatHanh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("CheckExistVanBanDen", soVanBanParameter, dateNgayPhatHanhParameter);
        }
    
        public virtual int AddGDVanBanDen(Nullable<System.Guid> id, Nullable<System.DateTime> dateNgayNhan, Nullable<System.Guid> idCoQuanBanHanhVanBan, Nullable<System.Guid> idLoaiVanBan, Nullable<System.Guid> idLinhVucBanHanh, string soVanBan, Nullable<System.DateTime> dateNgayPhatHanh, string trichYeuVanBan, string commentGD, string numberSoCongVan, Nullable<System.Guid> iDDonViChuTri, Nullable<System.Guid> iDDonVIPhoiHop, Nullable<System.DateTime> dateNgayChiDao, Nullable<System.DateTime> dateNgayPhaiHoanThanh, Nullable<bool> phaiBaoCao, string nguoiNhanVanBan, Nullable<System.DateTime> dateChuyenVanBanToiDonVi, string hoanThanh, string chuaHoanThanh, string dangThucHien, string chuaThucHien, string thucHienCham, string ketThucCongViec, string tomTatKetQua, string patition, string taiLIeuDinhKem, Nullable<System.Guid> idCanBoNhap, Nullable<System.DateTime> dateHoanThanh, Nullable<System.DateTime> createDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var dateNgayNhanParameter = dateNgayNhan.HasValue ?
                new ObjectParameter("DateNgayNhan", dateNgayNhan) :
                new ObjectParameter("DateNgayNhan", typeof(System.DateTime));
    
            var idCoQuanBanHanhVanBanParameter = idCoQuanBanHanhVanBan.HasValue ?
                new ObjectParameter("IdCoQuanBanHanhVanBan", idCoQuanBanHanhVanBan) :
                new ObjectParameter("IdCoQuanBanHanhVanBan", typeof(System.Guid));
    
            var idLoaiVanBanParameter = idLoaiVanBan.HasValue ?
                new ObjectParameter("IdLoaiVanBan", idLoaiVanBan) :
                new ObjectParameter("IdLoaiVanBan", typeof(System.Guid));
    
            var idLinhVucBanHanhParameter = idLinhVucBanHanh.HasValue ?
                new ObjectParameter("IdLinhVucBanHanh", idLinhVucBanHanh) :
                new ObjectParameter("IdLinhVucBanHanh", typeof(System.Guid));
    
            var soVanBanParameter = soVanBan != null ?
                new ObjectParameter("SoVanBan", soVanBan) :
                new ObjectParameter("SoVanBan", typeof(string));
    
            var dateNgayPhatHanhParameter = dateNgayPhatHanh.HasValue ?
                new ObjectParameter("DateNgayPhatHanh", dateNgayPhatHanh) :
                new ObjectParameter("DateNgayPhatHanh", typeof(System.DateTime));
    
            var trichYeuVanBanParameter = trichYeuVanBan != null ?
                new ObjectParameter("TrichYeuVanBan", trichYeuVanBan) :
                new ObjectParameter("TrichYeuVanBan", typeof(string));
    
            var commentGDParameter = commentGD != null ?
                new ObjectParameter("CommentGD", commentGD) :
                new ObjectParameter("CommentGD", typeof(string));
    
            var numberSoCongVanParameter = numberSoCongVan != null ?
                new ObjectParameter("NumberSoCongVan", numberSoCongVan) :
                new ObjectParameter("NumberSoCongVan", typeof(string));
    
            var iDDonViChuTriParameter = iDDonViChuTri.HasValue ?
                new ObjectParameter("IDDonViChuTri", iDDonViChuTri) :
                new ObjectParameter("IDDonViChuTri", typeof(System.Guid));
    
            var iDDonVIPhoiHopParameter = iDDonVIPhoiHop.HasValue ?
                new ObjectParameter("IDDonVIPhoiHop", iDDonVIPhoiHop) :
                new ObjectParameter("IDDonVIPhoiHop", typeof(System.Guid));
    
            var dateNgayChiDaoParameter = dateNgayChiDao.HasValue ?
                new ObjectParameter("DateNgayChiDao", dateNgayChiDao) :
                new ObjectParameter("DateNgayChiDao", typeof(System.DateTime));
    
            var dateNgayPhaiHoanThanhParameter = dateNgayPhaiHoanThanh.HasValue ?
                new ObjectParameter("DateNgayPhaiHoanThanh", dateNgayPhaiHoanThanh) :
                new ObjectParameter("DateNgayPhaiHoanThanh", typeof(System.DateTime));
    
            var phaiBaoCaoParameter = phaiBaoCao.HasValue ?
                new ObjectParameter("PhaiBaoCao", phaiBaoCao) :
                new ObjectParameter("PhaiBaoCao", typeof(bool));
    
            var nguoiNhanVanBanParameter = nguoiNhanVanBan != null ?
                new ObjectParameter("NguoiNhanVanBan", nguoiNhanVanBan) :
                new ObjectParameter("NguoiNhanVanBan", typeof(string));
    
            var dateChuyenVanBanToiDonViParameter = dateChuyenVanBanToiDonVi.HasValue ?
                new ObjectParameter("DateChuyenVanBanToiDonVi", dateChuyenVanBanToiDonVi) :
                new ObjectParameter("DateChuyenVanBanToiDonVi", typeof(System.DateTime));
    
            var hoanThanhParameter = hoanThanh != null ?
                new ObjectParameter("HoanThanh", hoanThanh) :
                new ObjectParameter("HoanThanh", typeof(string));
    
            var chuaHoanThanhParameter = chuaHoanThanh != null ?
                new ObjectParameter("ChuaHoanThanh", chuaHoanThanh) :
                new ObjectParameter("ChuaHoanThanh", typeof(string));
    
            var dangThucHienParameter = dangThucHien != null ?
                new ObjectParameter("DangThucHien", dangThucHien) :
                new ObjectParameter("DangThucHien", typeof(string));
    
            var chuaThucHienParameter = chuaThucHien != null ?
                new ObjectParameter("ChuaThucHien", chuaThucHien) :
                new ObjectParameter("ChuaThucHien", typeof(string));
    
            var thucHienChamParameter = thucHienCham != null ?
                new ObjectParameter("ThucHienCham", thucHienCham) :
                new ObjectParameter("ThucHienCham", typeof(string));
    
            var ketThucCongViecParameter = ketThucCongViec != null ?
                new ObjectParameter("KetThucCongViec", ketThucCongViec) :
                new ObjectParameter("KetThucCongViec", typeof(string));
    
            var tomTatKetQuaParameter = tomTatKetQua != null ?
                new ObjectParameter("TomTatKetQua", tomTatKetQua) :
                new ObjectParameter("TomTatKetQua", typeof(string));
    
            var patitionParameter = patition != null ?
                new ObjectParameter("Patition", patition) :
                new ObjectParameter("Patition", typeof(string));
    
            var taiLIeuDinhKemParameter = taiLIeuDinhKem != null ?
                new ObjectParameter("TaiLIeuDinhKem", taiLIeuDinhKem) :
                new ObjectParameter("TaiLIeuDinhKem", typeof(string));
    
            var idCanBoNhapParameter = idCanBoNhap.HasValue ?
                new ObjectParameter("IdCanBoNhap", idCanBoNhap) :
                new ObjectParameter("IdCanBoNhap", typeof(System.Guid));
    
            var dateHoanThanhParameter = dateHoanThanh.HasValue ?
                new ObjectParameter("DateHoanThanh", dateHoanThanh) :
                new ObjectParameter("DateHoanThanh", typeof(System.DateTime));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddGDVanBanDen", idParameter, dateNgayNhanParameter, idCoQuanBanHanhVanBanParameter, idLoaiVanBanParameter, idLinhVucBanHanhParameter, soVanBanParameter, dateNgayPhatHanhParameter, trichYeuVanBanParameter, commentGDParameter, numberSoCongVanParameter, iDDonViChuTriParameter, iDDonVIPhoiHopParameter, dateNgayChiDaoParameter, dateNgayPhaiHoanThanhParameter, phaiBaoCaoParameter, nguoiNhanVanBanParameter, dateChuyenVanBanToiDonViParameter, hoanThanhParameter, chuaHoanThanhParameter, dangThucHienParameter, chuaThucHienParameter, thucHienChamParameter, ketThucCongViecParameter, tomTatKetQuaParameter, patitionParameter, taiLIeuDinhKemParameter, idCanBoNhapParameter, dateHoanThanhParameter, createDateParameter);
        }
    
        public virtual int DeleteGDVanBanDen(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteGDVanBanDen", idParameter);
        }
    
        public virtual int EditGDVanBanDen(Nullable<System.Guid> id, Nullable<System.DateTime> dateNgayNhan, Nullable<System.Guid> idCoQuanBanHanhVanBan, Nullable<System.Guid> idLoaiVanBan, Nullable<System.Guid> idLinhVucBanHanh, string soVanBan, Nullable<System.DateTime> dateNgayPhatHanh, string trichYeuVanBan, string commentGD, string numberSoCongVan, Nullable<System.Guid> iDDonViChuTri, Nullable<System.Guid> iDDonVIPhoiHop, Nullable<System.DateTime> dateNgayChiDao, Nullable<System.DateTime> dateNgayPhaiHoanThanh, Nullable<bool> phaiBaoCao, string nguoiNhanVanBan, Nullable<System.DateTime> dateChuyenVanBanToiDonVi, string hoanThanh, string chuaHoanThanh, string dangThucHien, string chuaThucHien, string thucHienCham, string ketThucCongViec, string tomTatKetQua, string patition, string taiLIeuDinhKem, Nullable<System.DateTime> dateHoanThanh)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var dateNgayNhanParameter = dateNgayNhan.HasValue ?
                new ObjectParameter("DateNgayNhan", dateNgayNhan) :
                new ObjectParameter("DateNgayNhan", typeof(System.DateTime));
    
            var idCoQuanBanHanhVanBanParameter = idCoQuanBanHanhVanBan.HasValue ?
                new ObjectParameter("IdCoQuanBanHanhVanBan", idCoQuanBanHanhVanBan) :
                new ObjectParameter("IdCoQuanBanHanhVanBan", typeof(System.Guid));
    
            var idLoaiVanBanParameter = idLoaiVanBan.HasValue ?
                new ObjectParameter("IdLoaiVanBan", idLoaiVanBan) :
                new ObjectParameter("IdLoaiVanBan", typeof(System.Guid));
    
            var idLinhVucBanHanhParameter = idLinhVucBanHanh.HasValue ?
                new ObjectParameter("IdLinhVucBanHanh", idLinhVucBanHanh) :
                new ObjectParameter("IdLinhVucBanHanh", typeof(System.Guid));
    
            var soVanBanParameter = soVanBan != null ?
                new ObjectParameter("SoVanBan", soVanBan) :
                new ObjectParameter("SoVanBan", typeof(string));
    
            var dateNgayPhatHanhParameter = dateNgayPhatHanh.HasValue ?
                new ObjectParameter("DateNgayPhatHanh", dateNgayPhatHanh) :
                new ObjectParameter("DateNgayPhatHanh", typeof(System.DateTime));
    
            var trichYeuVanBanParameter = trichYeuVanBan != null ?
                new ObjectParameter("TrichYeuVanBan", trichYeuVanBan) :
                new ObjectParameter("TrichYeuVanBan", typeof(string));
    
            var commentGDParameter = commentGD != null ?
                new ObjectParameter("CommentGD", commentGD) :
                new ObjectParameter("CommentGD", typeof(string));
    
            var numberSoCongVanParameter = numberSoCongVan != null ?
                new ObjectParameter("NumberSoCongVan", numberSoCongVan) :
                new ObjectParameter("NumberSoCongVan", typeof(string));
    
            var iDDonViChuTriParameter = iDDonViChuTri.HasValue ?
                new ObjectParameter("IDDonViChuTri", iDDonViChuTri) :
                new ObjectParameter("IDDonViChuTri", typeof(System.Guid));
    
            var iDDonVIPhoiHopParameter = iDDonVIPhoiHop.HasValue ?
                new ObjectParameter("IDDonVIPhoiHop", iDDonVIPhoiHop) :
                new ObjectParameter("IDDonVIPhoiHop", typeof(System.Guid));
    
            var dateNgayChiDaoParameter = dateNgayChiDao.HasValue ?
                new ObjectParameter("DateNgayChiDao", dateNgayChiDao) :
                new ObjectParameter("DateNgayChiDao", typeof(System.DateTime));
    
            var dateNgayPhaiHoanThanhParameter = dateNgayPhaiHoanThanh.HasValue ?
                new ObjectParameter("DateNgayPhaiHoanThanh", dateNgayPhaiHoanThanh) :
                new ObjectParameter("DateNgayPhaiHoanThanh", typeof(System.DateTime));
    
            var phaiBaoCaoParameter = phaiBaoCao.HasValue ?
                new ObjectParameter("PhaiBaoCao", phaiBaoCao) :
                new ObjectParameter("PhaiBaoCao", typeof(bool));
    
            var nguoiNhanVanBanParameter = nguoiNhanVanBan != null ?
                new ObjectParameter("NguoiNhanVanBan", nguoiNhanVanBan) :
                new ObjectParameter("NguoiNhanVanBan", typeof(string));
    
            var dateChuyenVanBanToiDonViParameter = dateChuyenVanBanToiDonVi.HasValue ?
                new ObjectParameter("DateChuyenVanBanToiDonVi", dateChuyenVanBanToiDonVi) :
                new ObjectParameter("DateChuyenVanBanToiDonVi", typeof(System.DateTime));
    
            var hoanThanhParameter = hoanThanh != null ?
                new ObjectParameter("HoanThanh", hoanThanh) :
                new ObjectParameter("HoanThanh", typeof(string));
    
            var chuaHoanThanhParameter = chuaHoanThanh != null ?
                new ObjectParameter("ChuaHoanThanh", chuaHoanThanh) :
                new ObjectParameter("ChuaHoanThanh", typeof(string));
    
            var dangThucHienParameter = dangThucHien != null ?
                new ObjectParameter("DangThucHien", dangThucHien) :
                new ObjectParameter("DangThucHien", typeof(string));
    
            var chuaThucHienParameter = chuaThucHien != null ?
                new ObjectParameter("ChuaThucHien", chuaThucHien) :
                new ObjectParameter("ChuaThucHien", typeof(string));
    
            var thucHienChamParameter = thucHienCham != null ?
                new ObjectParameter("ThucHienCham", thucHienCham) :
                new ObjectParameter("ThucHienCham", typeof(string));
    
            var ketThucCongViecParameter = ketThucCongViec != null ?
                new ObjectParameter("KetThucCongViec", ketThucCongViec) :
                new ObjectParameter("KetThucCongViec", typeof(string));
    
            var tomTatKetQuaParameter = tomTatKetQua != null ?
                new ObjectParameter("TomTatKetQua", tomTatKetQua) :
                new ObjectParameter("TomTatKetQua", typeof(string));
    
            var patitionParameter = patition != null ?
                new ObjectParameter("Patition", patition) :
                new ObjectParameter("Patition", typeof(string));
    
            var taiLIeuDinhKemParameter = taiLIeuDinhKem != null ?
                new ObjectParameter("TaiLIeuDinhKem", taiLIeuDinhKem) :
                new ObjectParameter("TaiLIeuDinhKem", typeof(string));
    
            var dateHoanThanhParameter = dateHoanThanh.HasValue ?
                new ObjectParameter("DateHoanThanh", dateHoanThanh) :
                new ObjectParameter("DateHoanThanh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditGDVanBanDen", idParameter, dateNgayNhanParameter, idCoQuanBanHanhVanBanParameter, idLoaiVanBanParameter, idLinhVucBanHanhParameter, soVanBanParameter, dateNgayPhatHanhParameter, trichYeuVanBanParameter, commentGDParameter, numberSoCongVanParameter, iDDonViChuTriParameter, iDDonVIPhoiHopParameter, dateNgayChiDaoParameter, dateNgayPhaiHoanThanhParameter, phaiBaoCaoParameter, nguoiNhanVanBanParameter, dateChuyenVanBanToiDonViParameter, hoanThanhParameter, chuaHoanThanhParameter, dangThucHienParameter, chuaThucHienParameter, thucHienChamParameter, ketThucCongViecParameter, tomTatKetQuaParameter, patitionParameter, taiLIeuDinhKemParameter, dateHoanThanhParameter);
        }
    
        public virtual ObjectResult<GetOneGDVanBanDen_Result> GetOneGDVanBanDen(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneGDVanBanDen_Result>("GetOneGDVanBanDen", idParameter);
        }
    
        public virtual int GetAllViewDonViVaCoQuan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAllViewDonViVaCoQuan");
        }
    
        public virtual int AddCoQuanBanHanhVanBan(Nullable<System.Guid> id, string tenCoQuan, string kyHieu, Nullable<bool> inOrOut, string printname, Nullable<System.DateTime> createdate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var tenCoQuanParameter = tenCoQuan != null ?
                new ObjectParameter("TenCoQuan", tenCoQuan) :
                new ObjectParameter("TenCoQuan", typeof(string));
    
            var kyHieuParameter = kyHieu != null ?
                new ObjectParameter("KyHieu", kyHieu) :
                new ObjectParameter("KyHieu", typeof(string));
    
            var inOrOutParameter = inOrOut.HasValue ?
                new ObjectParameter("InOrOut", inOrOut) :
                new ObjectParameter("InOrOut", typeof(bool));
    
            var printnameParameter = printname != null ?
                new ObjectParameter("Printname", printname) :
                new ObjectParameter("Printname", typeof(string));
    
            var createdateParameter = createdate.HasValue ?
                new ObjectParameter("Createdate", createdate) :
                new ObjectParameter("Createdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCoQuanBanHanhVanBan", idParameter, tenCoQuanParameter, kyHieuParameter, inOrOutParameter, printnameParameter, createdateParameter);
        }
    
        public virtual int DeleteCoQuanBanHanhVanBan(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCoQuanBanHanhVanBan", idParameter);
        }
    
        public virtual int EditCoQuanBanHanhVanBan(Nullable<System.Guid> id, string tenCoQuan, string kyHieu, Nullable<bool> inOrOut, string printName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var tenCoQuanParameter = tenCoQuan != null ?
                new ObjectParameter("TenCoQuan", tenCoQuan) :
                new ObjectParameter("TenCoQuan", typeof(string));
    
            var kyHieuParameter = kyHieu != null ?
                new ObjectParameter("KyHieu", kyHieu) :
                new ObjectParameter("KyHieu", typeof(string));
    
            var inOrOutParameter = inOrOut.HasValue ?
                new ObjectParameter("InOrOut", inOrOut) :
                new ObjectParameter("InOrOut", typeof(bool));
    
            var printNameParameter = printName != null ?
                new ObjectParameter("PrintName", printName) :
                new ObjectParameter("PrintName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditCoQuanBanHanhVanBan", idParameter, tenCoQuanParameter, kyHieuParameter, inOrOutParameter, printNameParameter);
        }
    
        public virtual ObjectResult<GetAllCoQuanBanhanhVanBan_Result> GetAllCoQuanBanhanhVanBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCoQuanBanhanhVanBan_Result>("GetAllCoQuanBanhanhVanBan");
        }
    
        public virtual ObjectResult<GetOneCoQuanbanHanhVanBan_Result> GetOneCoQuanbanHanhVanBan(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneCoQuanbanHanhVanBan_Result>("GetOneCoQuanbanHanhVanBan", idParameter);
        }
    
        public virtual int AddDonVi(Nullable<System.Guid> id, string tenDonVi, string maDonVi, Nullable<bool> inOrOut, string printName, Nullable<System.DateTime> createdate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var tenDonViParameter = tenDonVi != null ?
                new ObjectParameter("TenDonVi", tenDonVi) :
                new ObjectParameter("TenDonVi", typeof(string));
    
            var maDonViParameter = maDonVi != null ?
                new ObjectParameter("MaDonVi", maDonVi) :
                new ObjectParameter("MaDonVi", typeof(string));
    
            var inOrOutParameter = inOrOut.HasValue ?
                new ObjectParameter("InOrOut", inOrOut) :
                new ObjectParameter("InOrOut", typeof(bool));
    
            var printNameParameter = printName != null ?
                new ObjectParameter("PrintName", printName) :
                new ObjectParameter("PrintName", typeof(string));
    
            var createdateParameter = createdate.HasValue ?
                new ObjectParameter("Createdate", createdate) :
                new ObjectParameter("Createdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddDonVi", idParameter, tenDonViParameter, maDonViParameter, inOrOutParameter, printNameParameter, createdateParameter);
        }
    
        public virtual int DeleteDonVi(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteDonVi", idParameter);
        }
    
        public virtual int EditDonVi(Nullable<System.Guid> id, string tenDonVi, string maDonVi, Nullable<bool> inOrOut, string printName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var tenDonViParameter = tenDonVi != null ?
                new ObjectParameter("TenDonVi", tenDonVi) :
                new ObjectParameter("TenDonVi", typeof(string));
    
            var maDonViParameter = maDonVi != null ?
                new ObjectParameter("MaDonVi", maDonVi) :
                new ObjectParameter("MaDonVi", typeof(string));
    
            var inOrOutParameter = inOrOut.HasValue ?
                new ObjectParameter("InOrOut", inOrOut) :
                new ObjectParameter("InOrOut", typeof(bool));
    
            var printNameParameter = printName != null ?
                new ObjectParameter("PrintName", printName) :
                new ObjectParameter("PrintName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditDonVi", idParameter, tenDonViParameter, maDonViParameter, inOrOutParameter, printNameParameter);
        }
    
        public virtual ObjectResult<GetAllDonvi_Result> GetAllDonvi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllDonvi_Result>("GetAllDonvi");
        }
    
        public virtual ObjectResult<GetOneDonVi_Result> GetOneDonVi(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneDonVi_Result>("GetOneDonVi", idParameter);
        }
    
        public virtual ObjectResult<GetAllCoQuanVaDonVi_Result> GetAllCoQuanVaDonVi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCoQuanVaDonVi_Result>("GetAllCoQuanVaDonVi");
        }
    
        public virtual ObjectResult<GetAllGDKyBanHanh_Result> GetAllGDKyBanHanh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllGDKyBanHanh_Result>("GetAllGDKyBanHanh");
        }
    
        public virtual ObjectResult<ViewGDVanBanDenGDNoComment_Result> ViewGDVanBanDenGDNoComment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewGDVanBanDenGDNoComment_Result>("ViewGDVanBanDenGDNoComment");
        }
    
        public virtual ObjectResult<ViewGDVanBanDenHetHan_Result> ViewGDVanBanDenHetHan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewGDVanBanDenHetHan_Result>("ViewGDVanBanDenHetHan");
        }
    
        public virtual ObjectResult<ViewGDVanBanDenSapHetHan_Result> ViewGDVanBanDenSapHetHan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewGDVanBanDenSapHetHan_Result>("ViewGDVanBanDenSapHetHan");
        }
    
        public virtual ObjectResult<GetAllGDVanBanDen_Result> GetAllGDVanBanDen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllGDVanBanDen_Result>("GetAllGDVanBanDen");
        }
    
        public virtual ObjectResult<ExportVanBan_Result> ExportVanBan(Nullable<System.Guid> id, Nullable<System.DateTime> dateTuNgay, Nullable<System.DateTime> dateDenNgay)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(System.Guid));
    
            var dateTuNgayParameter = dateTuNgay.HasValue ?
                new ObjectParameter("DateTuNgay", dateTuNgay) :
                new ObjectParameter("DateTuNgay", typeof(System.DateTime));
    
            var dateDenNgayParameter = dateDenNgay.HasValue ?
                new ObjectParameter("DateDenNgay", dateDenNgay) :
                new ObjectParameter("DateDenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExportVanBan_Result>("ExportVanBan", idParameter, dateTuNgayParameter, dateDenNgayParameter);
        }
    }
}
