//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoDoiVanBan
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdGDVanBanDen { get; set; }
        public string CanBoThuLy { get; set; }
        public string CommentGD { get; set; }
        public string PGDPhuTrach { get; set; }
        public Nullable<System.Guid> IdDonViChucNang { get; set; }
        public Nullable<System.Guid> IdLanhDaoPhuTrach { get; set; }
        public string TienDoCongViec { get; set; }
        public string NumberDate { get; set; }
        public string TaiLieuDinhKem { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    
        public virtual GDVanBanDen GDVanBanDen { get; set; }
    }
}
