//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDonViVaCoQuan
    {
        public System.Guid Id { get; set; }
        public Nullable<bool> InOrOut { get; set; }
        public string KyHieu { get; set; }
        public string TenCoQuan { get; set; }
        public string PrintName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
