//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVanBan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGDKyBanHanh
    {
        public System.Guid Id { get; set; }
        public string NameLinhVuc { get; set; }
        public string NameVanBan { get; set; }
        public string TenDonVi { get; set; }
        public string TenLanhDao { get; set; }
        public string CanBoThamMuu { get; set; }
        public Nullable<System.DateTime> DateTrinhVanBan { get; set; }
        public Nullable<System.DateTime> DateKyVanBan { get; set; }
        public string NumberVanBan { get; set; }
        public Nullable<System.DateTime> DateVanBan { get; set; }
        public string TrichYeuVanBan { get; set; }
        public string TaiLieuDinhKem { get; set; }
        public System.Guid IdCanBoNhap { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
